---
- hosts: all
  become: true
  vars_files: 
    - vars/deploysite.yml
  tasks:
    - name: Find Service package
      find: paths="{{ webroot }}" patterns="*.tar.gz"
      register: find_result

    - name: Unpack tarball
      ansible.builtin.unarchive:
        src: "{{ item.path }}"
        dest: "{{ webroot }}"
        remote_src: yes
      with_items: "{{ find_result.files }}"

    - name: set fact
      set_fact:
        mysql_user:  |
          {% for container in morpheus["instance"]["apps"][0]["instances"] %} 
            {% if container["customOptions"]["mysqlAdminUsername"] is defined  %}
              {{ container["customOptions"]["mysqlAdminUsername"] }}
            {%  endif %}
          {% endfor %}

    - name: test
      debug:
        msg: "{{ mysql_user }}"

    - name: WP-Config
      replace:
        path: "{{ wordpress_config_file }}"
        regexp: 'username_here'
        replace: "{{ mysql_user }}"