---
- hosts: all
  become: true
  tasks:
    - name: Find Service package
      find: paths="/var/www/html" patterns="*.tar.gz"
      register: find_result

    - name: Unpack tarball
      ansible.builtin.unarchive:
        src: "{{ item.path }}"
        dest: /var/www/html/
        remote_src: yes
      with_items: "{{ find_result.files }}"

    - name: set fact
      set_fact:
        mysql_user:  |
          {% for container in morpheus["instance"]["apps"][0]["instances"] %} 
            {% if container["customOptions"] is defined %}
              {% if container["customOptions"].mysqlAdminUsername is dict %}
                Dictionary
              {% else %}
                Not
              {% endif %}
            {%  endif %}
          {% endfor %}

    - name: test
      debug:
        msg: "{{ mysql_user }}"