---
- hosts: all
  become: true
  vars_files: 
    - vars/deploysite.yml
  tasks:
    - name: Find Service package
      find: paths="{{ webroot }}" patterns="*.tar.gz"
      register: find_result

    - name: Unpack tarball
      ansible.builtin.unarchive:
        src: "{{ item.path }}"
        dest: "{{ webroot }}"
        remote_src: yes
      with_items: "{{ find_result.files }}"

    - name: set fact mysql user
      set_fact:
        mysql_user:  |
          {%- for container in morpheus["instance"]["apps"][0]["instances"] -%} 
            {%- if container["customOptions"]["mysqlAdminUsername"] is defined  -%}
          {{- container["customOptions"]["mysqlAdminUsername"] | trim -}}
            {%- endif -%}
          {%- endfor -%}

    - name: set fact mysql password
      set_fact:
        mysql_pw:  |
          {%- for container in morpheus["instance"]["apps"][0]["instances"] -%} 
            {%- if container["customOptions"]["mysqlAdminPw"] is defined  -%}
          {{- container["customOptions"]["mysqlAdminPw"] | trim -}}
            {%- endif -%}
          {%- endfor -%}

    - name: set fact mysql db name
      set_fact:
        mysql_db:  |
          {%- for container in morpheus["instance"]["apps"][0]["instances"] -%} 
            {%- if container["customOptions"]["mysqlDbName"] is defined  -%}
          {{- container["customOptions"]["mysqlDbName"] | trim -}}
            {%- endif -%}
          {%- endfor -%}

    - name: test
      debug:
        msg: "{{ mysql_user }}"

    - name: WP-Config-User
      replace:
        path: "{{ wordpress_config_file }}"
        regexp: 'username_here'
        replace: "{{ mysql_user  | replace('\n', '') }}"

    - name: WP-Config-PW
      replace:
        path: "{{ wordpress_config_file }}"
        regexp: 'password_here'
        replace: "{{ mysql_pw  | replace('\n', '') }}"

    - name: WP-Config-DB
      replace:
        path: "{{ wordpress_config_file }}"
        regexp: 'database_name_here'
        replace: "{{ mysql_db  | replace('\n', '') }}"

    - name: WP-Config-IP
      replace:
        path: "{{ wordpress_config_file }}"
        regexp: 'localhost'
        replace: "{{ lookup('env', 'MYSQL_IP') }}"
