- src: https://github.com/geerlingguy/ansible-role-apache
  name: apache

- src: https://github.com/geerlingguy/ansible-role-php
  name: php

- src: https://github.com/geerlingguy/ansible-role-mysql
  name: mysql

- src: https://github.com/geerlingguy/ansible-role-php-mysql
  name: php-mysql